language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=adafruit_feather_m0

script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  - platformio ci --board=$BOARD --lib=. $PWD/Arduino\ Code/ChickenCoopEnviroment/ChickenCoopEnviroment.ino
  
notifications:
  email:
    on_success: change
    on_failure: change