language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=adafruit_feather_m0

script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  - pio lib install "Adafruit Unified Sensor"
  - pio lib install "Ethernet2"
  - pio lib install "PubSubClient"
  - pio lib install "Adafruit BME280 Library"
  - pio lib install "Adafruit Motor Shield library"
  - pio lib install "Adafruit MCP23017 Arduino Library"
  - platformio lib -g install  https://github.com/sfrwmaker/sunMoon/archive/master.zip
  - platformio lib -g install  https://github.com/JChristensen/Timezone/archive/master.zip
  - pio lib install "RTClib"
  - pio lib install "MAX31850 OneWire"
  - pio lib install "Adafruit Motor Shield V2 Library"
  - pio lib install "U8g2"
  - pio lib install "Time"

  - platformio ci --board=$BOARD --lib=$PWD/Arduino\ Code/ChickenCoopEnviroment $PWD/Arduino\ Code/ChickenCoopEnviroment/ChickenCoopEnviroment.ino
  
notifications:
  email:
    on_success: change
    on_failure: change