language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=adafruit_feather_m0

script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  - platformio lib -g install  https://github.com/adafruit/Adafruit_Sensor/archive/master.zip
  - platformio lib -g install  http://downloads.arduino.cc/libraries/github.com/adafruit/Ethernet2-1.0.4.zip
  - platformio lib -g install  http://downloads.arduino.cc/libraries/github.com/knolleary/PubSubClient-2.6.0.zip
  - platformio lib -g install  https://github.com/adafruit/Adafruit_BME280_Library/archive/master.zip
  - platformio lib -g install  https://github.com/adafruit/Adafruit-Motor-Shield-library/archive/master.zip
  - platformio lib -g install  https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library/archive/master.zip
  - platformio lib -g install  https://github.com/olikraus/u8glib/archive/master.zip
  - platformio lib -g install  https://github.com/sfrwmaker/sunMoon/archive/master.zip
  - platformio lib -g install  https://github.com/JChristensen/Timezone/archive/master.zip
  - platformio lib -g install  https://github.com/adafruit/RTClib/archive/master.zip
  - platformio lib -g install  http://downloads.arduino.cc/libraries/github.com/PaulStoffregen/OneWire-2.3.4.zip
  - platformio lib -g install  https://github.com/adafruit/Adafruit_Motor_Shield_V2_Library/archive/master.zip

  - platformio ci --board=$BOARD --lib=$PWD/Arduino\ Code/ChickenCoopEnviroment $PWD/Arduino\ Code/ChickenCoopEnviroment/ChickenCoopEnviroment.ino
  
notifications:
  email:
    on_success: change
    on_failure: change